---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.8.x
    - 1.9.x
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "jrgm0ztM3HftDjOIx6zgaRVR+nklYVItHgD/7SnIgA+qE0iscvVnb7nueEyyvBlH6opUvRecH+dAIjk6D9hw7aF1PrUHiEf/4LA7AbXce0Tl/II3izHhB0NCH4M7lN+99iPCqVDy0ypMeN6kiEby1SbSk+r1BFsngf3LSii60kQ9eoaXjtnR5WFHaB6IvDD6RGdxMxpYddaFTw8OG9+HykXxwS97Fd+WM3nWmtDXrWUNoVf3HgbYvaT8phjL6vqqbKA0LAPlmN9z8sg1pP3MkahTjgNjyGaYwfk4mKjdNECgCOwUfCpNUgzeEhlIqUGJugHW18DDC4VvhhrdEFA5Z9QqCIOJ31vL/fFqxo6d6ftifAWgtztSS3SDHwfZWOnOFVTkJc9ndy6moKKe6VwOXknSGHDsxN3NZpfH/UUZlxfi8BaTJDlwLLJ9fNIMdOPOIGwcKtT8oyrx8RZ9kw230R6a/336FQ9FgYgmLRwdfp30NbUvQ52fjI+duX5pEkrooYfw95WZ/vWc/9gsy1mLF8c2ywHciUEnuh3vcBsBOph+Wy/ZW05OYbDo2CczgFJISUEjeqCYX3brwaJcPYbhuwyqwtHESrU9dXj2vctJC4jjOtfifjdSXk77S9fU4q+G7rbDkwGMT0DLyUKrY3DBSHCKP3BqQaNKpbT4evg/byw="
    file:
      - cross/sshb0t-linux-amd64.md5
      - cross/sshb0t-windows-386.sha256
      - cross/sshb0t-linux-arm
      - cross/sshb0t-darwin-amd64.md5
      - cross/sshb0t-darwin-amd64
      - cross/sshb0t-solaris-amd64.md5
      - cross/sshb0t-linux-arm64.sha256
      - cross/sshb0t-linux-arm.sha256
      - cross/sshb0t-linux-386.sha256
      - cross/sshb0t-darwin-386.md5
      - cross/sshb0t-windows-386.md5
      - cross/sshb0t-freebsd-amd64.md5
      - cross/sshb0t-linux-arm64.md5
      - cross/sshb0t-linux-arm64
      - cross/sshb0t-freebsd-amd64.sha256
      - cross/sshb0t-freebsd-386.md5
      - cross/sshb0t-linux-amd64.sha256
      - cross/sshb0t-linux-386.md5
      - cross/sshb0t-freebsd-386
      - cross/sshb0t-solaris-amd64.sha256
      - cross/sshb0t-windows-amd64
      - cross/sshb0t-windows-amd64.md5
      - cross/sshb0t-windows-amd64.sha256
      - cross/sshb0t-linux-arm.md5
      - cross/sshb0t-darwin-386.sha256
      - cross/sshb0t-darwin-amd64.sha256
      - cross/sshb0t-windows-386
      - cross/sshb0t-solaris-amd64
      - cross/sshb0t-darwin-386
      - cross/sshb0t-linux-386
      - cross/sshb0t-freebsd-amd64
      - cross/sshb0t-freebsd-386.sha256
      - cross/sshb0t-linux-amd64
    skip_cleanup: true
    on:
      go: tip
      tags: true
